### ISSUE TITLE
Problème lecture

### ISSUE THREAD

**Issue by Jarvis-69** [victore447/M3uSportsFrance#1]
Je n'arrive pas à charger le fichier sur Kodi, peux-tu m'aider ?

**Comment by victore447** [comment]
👋Tout d'abord il faut autoriser Kodi a avoir accès au fichiers selon l'appareil utilisé (paramètre, applications,Kodi, puis en bas autorisations supplémentaires, et activé "autoriser la gestion de tout les fichiers".

☝️ L'addon👉 ["Pvr Iptv simple client" ](https://github.com/kodi-pvr/pvr.iptvsimple) de Kodi a évolué mais c'est le même principe que cette vidéo Youtube de 2018 qui montre comment charger un fichier M3u.
👉 [Vidéo Youtube ](https://youtube.com/watch?v=e0OhPGqS3CY)  ☝️Il faut mémoriser l'endroit où le fichier M3u a été copié.

**Pour la version récente de Pvr Iptv  il faut lire ce qui à été ajouté ✔️**
