### ISSUE TITLE
Problème de lecture

### ISSUE THREAD

**Issue by sylou59** [victore447/M3uSportsFrance#2]
Salut,
J'ai un soucis quand je charge une chaine exemple : RMC Sport 1, au bout de 15 secondes, cela arrête la lecture de RMC Sport 1 et ça passe à la chaine suivante RMC Sport 2 de manière automatique. Pourquoi ça passe à la chaîne suivante ?

**Comment by victore447** [comment]
👋 J'ai retester sur l'application "Tivimate" vers 2h du matin après votre message et ça marche correctement sans changer de chaine toute les 15 secondes.

👆Il faut  essayer sur d'autres applications téléchargeable sur l'accueil du Repo et ou sur Google play store etc...

☝️Si C'est  Kodi que vous utilisez les coupures de 15 secondes sont dû à l'utilisation par d'autres personnes aussi.✔️

**Comment by sylou59** [comment]
Bonsoir
Je suis actuellement sur Tivimate, au bout de 15-20 secondes, il y a un freeze de 1 seconde et ça reprend correctement. Vous avez ça aussi ?

**Comment by victore447** [comment]
👋 Si c'est tout le temps comme  ça de votre côté et que aucune fois cette playlist n'a pas fonctionné correctement,le problème vient de votre connexion internet etc...Et je ne peux rien faire pour vous.

**Comment by victore447** [comment]
👋
Changement url ✔️

**Comment by delabh514** [comment]
Salut, est-ce qu'il serait possible d'avoir d'autres chaines, autres que des chaines de sports (Des chaines Canadiennes par exemple) ?
Merci.

**Comment by victore447** [comment]
> Salut, est-ce qu'il serait possible d'avoir d'autres chaines, autres que des chaines de sports (Des chaines Canadiennes par exemple) ? Merci.


🖐️ les Url extraites de ces chaînes proviennent d'une liste StbEmu codes  qui ne contient pas de chaînes 🇨🇦. Il y a juste les pays 🇨🇵 🇪🇦 🇬🇧 et chaînes ⛔ adultes

☝️Comme elles sont sans coupure dans kodi,J'ai converti juste ces quelques chaînes avec une appli qui sniff ces sources vidéo.
Puis j'y ai intégré des Url  epg et icônes (ça Prend du temps) pour créé le présent fichier m3u et j'ai  partager ça sur Github.

👆On peut voir toutes ces chaînes 🇨🇵 🇪🇦 🇬🇧 sur l'appli 🖲️ **[Tivimate Iptv Player Google Play Store](https://play.google.com/store/apps/details?id=ar.tvplayer.tv&hl=fr&gl=US)**
 par exemple.
☝️Il faux récupérer sur ce 🖲️ **[LIEN](https://github.com/victore447/M3uSportsFrance/blob/main/M3uSportsFrance.m3u)**   l'url ( http://molccccc::8080 ) et l'adresse mac ( 00:1A:79: etc... )  puis ajouter cela  dans Portal Stalker de Tivimate ✔️

**Comment by untiiis** [comment]
Bonjour,
Est-ce que les chaînes fonctionnent, ou il y a un souci avec le serveur ?
